spring:
  application:
    name : garciaCutillasFranciscoJose_pruebaTecnicaTicarum
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:estacion_meteorologica_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html					 	